INSERT INTO Countries VALUES (1,'Afghanistan','AF','AFG');
INSERT INTO Countries VALUES (2,'Aland Islands','AX','ALA');
INSERT INTO Countries VALUES (3,'Albania','AL','ALB');
INSERT INTO Countries VALUES (4,'Algeria','DZ','DZA');
INSERT INTO Countries VALUES (5,'American Samoa','AS','ASM');
INSERT INTO Countries VALUES (6,'Andorra','AD','AND');
INSERT INTO Countries VALUES (	7	,	'Angola'	,	'AO'	,	'AGO')	;
INSERT INTO Countries VALUES (	8	,	'Anguilla'	,	'AI'	,	'AIA')	;
INSERT INTO Countries VALUES (	9	,	'Antarctica'	,	'AQ'	,	'ATA')	;
INSERT INTO Countries VALUES (	10	,	'Antigua and Barbuda'	,	'AG'	,	'ATG')	;
INSERT INTO Countries VALUES (	11	,	'Argentina'	,	'AR'	,	'ARG')	;
INSERT INTO Countries VALUES (	12	,	'Armenia'	,	'AM'	,	'ARM')	;
INSERT INTO Countries VALUES (	13	,	'Aruba'	,	'AW'	,	'ABW')	;
INSERT INTO Countries VALUES (	14	,	'Australia'	,	'AU'	,	'AUS')	;
INSERT INTO Countries VALUES (	15	,	'Austria'	,	'AT'	,	'AUT')	;
INSERT INTO Countries VALUES (	16	,	'Azerbaijan'	,	'AZ'	,	'AZE')	;
INSERT INTO Countries VALUES (	17	,	'Bahamas'	,	'BS'	,	'BHS')	;
INSERT INTO Countries VALUES (	18	,	'Bahrain'	,	'BH'	,	'BHR')	;
INSERT INTO Countries VALUES (	19	,	'Bangladesh'	,	'BD'	,	'BGD')	;
INSERT INTO Countries VALUES (	20	,	'Barbados'	,	'BB'	,	'BRB')	;
INSERT INTO Countries VALUES (	21	,	'Belarus'	,	'BY'	,	'BLR')	;
INSERT INTO Countries VALUES (	22	,	'Belgium'	,	'BE'	,	'BEL')	;
INSERT INTO Countries VALUES (	23	,	'Belize'	,	'BZ'	,	'BLZ')	;
INSERT INTO Countries VALUES (	24	,	'Benin'	,	'BJ'	,	'BEN')	;
INSERT INTO Countries VALUES (	25	,	'Bermuda'	,	'BM'	,	'BMU')	;
INSERT INTO Countries VALUES (	26	,	'Bhutan'	,	'BT'	,	'BTN')	;
INSERT INTO Countries VALUES (	27	,	'Bolivia'	,	'BO'	,	'BOL')	;
INSERT INTO Countries VALUES (	28	,	'Bonaire Sint Eustatius and Saba'	,	'BQ'	,	'BES')	;
INSERT INTO Countries VALUES (	29	,	'Bosnia and Herzegovina'	,	'BA'	,	'BIH')	;
INSERT INTO Countries VALUES (	30	,	'Botswana'	,	'BW'	,	'BWA')	;
INSERT INTO Countries VALUES (	31	,	'Bouvet Island'	,	'BV'	,	'BVT')	;
INSERT INTO Countries VALUES (	32	,	'Brazil'	,	'BR'	,	'BRA')	;
INSERT INTO Countries VALUES (	33	,	'British Indian Ocean Territory'	,	'IO'	,	'IOT')	;
INSERT INTO Countries VALUES (	34	,	'Brunei'	,	'BN'	,	'BRN')	;
INSERT INTO Countries VALUES (	35	,	'Bulgaria'	,	'BG'	,	'BGR')	;
INSERT INTO Countries VALUES (	36	,	'Burkina Faso'	,	'BF'	,	'BFA')	;
INSERT INTO Countries VALUES (	37	,	'Burundi'	,	'BI'	,	'BDI')	;
INSERT INTO Countries VALUES (	38	,	'Cambodia'	,	'KH'	,	'KHM')	;
INSERT INTO Countries VALUES (	39	,	'Cameroon'	,	'CM'	,	'CMR')	;
INSERT INTO Countries VALUES (	40	,	'Canada'	,	'CA'	,	'CAN')	;
INSERT INTO Countries VALUES (	41	,	'Cape Verde'	,	'CV'	,	'CPV')	;
INSERT INTO Countries VALUES (	42	,	'Cayman Islands'	,	'KY'	,	'CYM')	;
INSERT INTO Countries VALUES (	43	,	'Central African Republic'	,	'CF'	,	'CAF')	;
INSERT INTO Countries VALUES (	44	,	'Chad'	,	'TD'	,	'TCD')	;
INSERT INTO Countries VALUES (	45	,	'Chile'	,	'CL'	,	'CHL')	;
INSERT INTO Countries VALUES (	46	,	'China'	,	'CN'	,	'CHN')	;
INSERT INTO Countries VALUES (	47	,	'Christmas Island'	,	'CX'	,	'CXR')	;
INSERT INTO Countries VALUES (	48	,	'Cocos (Keeling) Islands'	,	'CC'	,	'CCK')	;
INSERT INTO Countries VALUES (	49	,	'Colombia'	,	'CO'	,	'COL')	;
INSERT INTO Countries VALUES (	50	,	'Comoros'	,	'KM'	,	'COM')	;
INSERT INTO Countries VALUES (	51	,	'Congo'	,	'CG'	,	'COG')	;
INSERT INTO Countries VALUES (	52	,	'Cook Islands'	,	'CK'	,	'COK')	;
INSERT INTO Countries VALUES (	53	,	'Costa Rica'	,	'CR'	,	'CRI')	;
INSERT INTO Countries VALUES (	54	,	'Ivory Coast'	,	'CI'	,	'CIV')	;
INSERT INTO Countries VALUES (	55	,	'Croatia'	,	'HR'	,	'HRV')	;
INSERT INTO Countries VALUES (	56	,	'Cuba'	,	'CU'	,	'CUB')	;
INSERT INTO Countries VALUES (	57	,	'Curacao'	,	'CW'	,	'CUW')	;
INSERT INTO Countries VALUES (	58	,	'Cyprus'	,	'CY'	,	'CYP')	;
INSERT INTO Countries VALUES (	59	,	'Czech Republic'	,	'CZ'	,	'CZE')	;
INSERT INTO Countries VALUES (	60	,	'Democratic Republic of the Congo'	,	'CD'	,	'COD')	;
INSERT INTO Countries VALUES (	61	,	'Denmark'	,	'DK'	,	'DNK')	;
INSERT INTO Countries VALUES (	62	,	'Djibouti'	,	'DJ'	,	'DJI')	;
INSERT INTO Countries VALUES (	63	,	'Dominica'	,	'DM'	,	'DMA')	;
INSERT INTO Countries VALUES (	64	,	'Dominican Republic'	,	'DO'	,	'DOM')	;
INSERT INTO Countries VALUES (	65	,	'Ecuador'	,	'EC'	,	'ECU')	;
INSERT INTO Countries VALUES (	66	,	'Egypt'	,	'EG'	,	'EGY')	;
INSERT INTO Countries VALUES (	67	,	'El Salvador'	,	'SV'	,	'SLV')	;
INSERT INTO Countries VALUES (	68	,	'Equatorial Guinea'	,	'GQ'	,	'GNQ')	;
INSERT INTO Countries VALUES (	69	,	'Eritrea'	,	'ER'	,	'ERI')	;
INSERT INTO Countries VALUES (	70	,	'Estonia'	,	'EE'	,	'EST')	;
INSERT INTO Countries VALUES (	71	,	'Ethiopia'	,	'ET'	,	'ETH')	;
INSERT INTO Countries VALUES (	72	,	'Falkland Islands (Malvinas)'	,	'FK'	,	'FLK')	;
INSERT INTO Countries VALUES (	73	,	'Faroe Islands'	,	'FO'	,	'FRO')	;
INSERT INTO Countries VALUES (	74	,	'Fiji'	,	'FJ'	,	'FJI')	;
INSERT INTO Countries VALUES (	75	,	'Finland'	,	'FI'	,	'FIN')	;
INSERT INTO Countries VALUES (	76	,	'France'	,	'FR'	,	'FRA')	;
INSERT INTO Countries VALUES (	77	,	'French Guiana'	,	'GF'	,	'GUF')	;
INSERT INTO Countries VALUES (	78	,	'French Polynesia'	,	'PF'	,	'PYF')	;
INSERT INTO Countries VALUES (	79	,	'French Southern Territories'	,	'TF'	,	'ATF')	;
INSERT INTO Countries VALUES (	80	,	'Gabon'	,	'GA'	,	'GAB')	;
INSERT INTO Countries VALUES (	81	,	'Gambia'	,	'GM'	,	'GMB')	;
INSERT INTO Countries VALUES (	82	,	'Georgia'	,	'GE'	,	'GEO')	;
INSERT INTO Countries VALUES (	83	,	'Germany'	,	'DE'	,	'DEU')	;
INSERT INTO Countries VALUES (	84	,	'Ghana'	,	'GH'	,	'GHA')	;
INSERT INTO Countries VALUES (	85	,	'Gibraltar'	,	'GI'	,	'GIB')	;
INSERT INTO Countries VALUES (	86	,	'Greece'	,	'GR'	,	'GRC')	;
INSERT INTO Countries VALUES (	87	,	'Greenland'	,	'GL'	,	'GRL')	;
INSERT INTO Countries VALUES (	88	,	'Grenada'	,	'GD'	,	'GRD')	;
INSERT INTO Countries VALUES (	89	,	'Guadaloupe'	,	'GP'	,	'GLP')	;
INSERT INTO Countries VALUES (	90	,	'Guam'	,	'GU'	,	'GUM')	;
INSERT INTO Countries VALUES (	91	,	'Guatemala'	,	'GT'	,	'GTM')	;
INSERT INTO Countries VALUES (	92	,	'Guernsey'	,	'GG'	,	'GGY')	;
INSERT INTO Countries VALUES (	93	,	'Guinea'	,	'GN'	,	'GIN')	;
INSERT INTO Countries VALUES (	94	,	'Guinea-Bissau'	,	'GW'	,	'GNB')	;
INSERT INTO Countries VALUES (	95	,	'Guyana'	,	'GY'	,	'GUY')	;
INSERT INTO Countries VALUES (	96	,	'Haiti'	,	'HT'	,	'HTI')	;
INSERT INTO Countries VALUES (	97	,	'Heard Island and McDonald Islands'	,	'HM'	,	'HMD')	;
INSERT INTO Countries VALUES (	98	,	'Honduras'	,	'HN'	,	'HND')	;
INSERT INTO Countries VALUES (	99	,	'Hong Kong'	,	'HK'	,	'HKG')	;
INSERT INTO Countries VALUES (	100	,	'Hungary'	,	'HU'	,	'HUN')	;
INSERT INTO Countries VALUES (	101	,	'Iceland'	,	'IS'	,	'ISL')	;
INSERT INTO Countries VALUES (	102	,	'India'	,	'IN'	,	'IND')	;
INSERT INTO Countries VALUES (	103	,	'Indonesia'	,	'ID'	,	'IDN')	;
INSERT INTO Countries VALUES (	104	,	'Iran'	,	'IR'	,	'IRN')	;
INSERT INTO Countries VALUES (	105	,	'Iraq'	,	'IQ'	,	'IRQ')	;
INSERT INTO Countries VALUES (	106	,	'Ireland'	,	'IE'	,	'IRL')	;
INSERT INTO Countries VALUES (	107	,	'Isle of Man'	,	'IM'	,	'IMN')	;
INSERT INTO Countries VALUES (	108	,	'Israel'	,	'IL'	,	'ISR')	;
INSERT INTO Countries VALUES (	109	,	'Italy'	,	'IT'	,	'ITA')	;
INSERT INTO Countries VALUES (	110	,	'Jamaica'	,	'JM'	,	'JAM')	;
INSERT INTO Countries VALUES (	111	,	'Japan'	,	'JP'	,	'JPN')	;
INSERT INTO Countries VALUES (	112	,	'Jersey'	,	'JE'	,	'JEY')	;
INSERT INTO Countries VALUES (	113	,	'Jordan'	,	'JO'	,	'JOR')	;
INSERT INTO Countries VALUES (	114	,	'Kazakhstan'	,	'KZ'	,	'KAZ')	;
INSERT INTO Countries VALUES (	115	,	'Kenya'	,	'KE'	,	'KEN')	;
INSERT INTO Countries VALUES (	116	,	'Kiribati'	,	'KI'	,	'KIR')	;
INSERT INTO Countries VALUES (	117	,	'Kosovo'	,	'XK'	,	'---')	;
INSERT INTO Countries VALUES (	118	,	'Kuwait'	,	'KW'	,	'KWT')	;
INSERT INTO Countries VALUES (	119	,	'Kyrgyzstan'	,	'KG'	,	'KGZ')	;
INSERT INTO Countries VALUES (	120	,	'Laos'	,	'LA'	,	'LAO')	;
INSERT INTO Countries VALUES (	121	,	'Latvia'	,	'LV'	,	'LVA')	;
INSERT INTO Countries VALUES (	122	,	'Lebanon'	,	'LB'	,	'LBN')	;
INSERT INTO Countries VALUES (	123	,	'Lesotho'	,	'LS'	,	'LSO')	;
INSERT INTO Countries VALUES (	124	,	'Liberia'	,	'LR'	,	'LBR')	;
INSERT INTO Countries VALUES (	125	,	'Libya'	,	'LY'	,	'LBY')	;
INSERT INTO Countries VALUES (	126	,	'Liechtenstein'	,	'LI'	,	'LIE')	;
INSERT INTO Countries VALUES (	127	,	'Lithuania'	,	'LT'	,	'LTU')	;
INSERT INTO Countries VALUES (	128	,	'Luxembourg'	,	'LU'	,	'LUX')	;
INSERT INTO Countries VALUES (	129	,	'Macao'	,	'MO'	,	'MAC')	;
INSERT INTO Countries VALUES (	130	,	'Macedonia'	,	'MK'	,	'MKD')	;
INSERT INTO Countries VALUES (	131	,	'Madagascar'	,	'MG'	,	'MDG')	;
INSERT INTO Countries VALUES (	132	,	'Malawi'	,	'MW'	,	'MWI')	;
INSERT INTO Countries VALUES (	133	,	'Malaysia'	,	'MY'	,	'MYS')	;
INSERT INTO Countries VALUES (	134	,	'Maldives'	,	'MV'	,	'MDV')	;
INSERT INTO Countries VALUES (	135	,	'Mali'	,	'ML'	,	'MLI')	;
INSERT INTO Countries VALUES (	136	,	'Malta'	,	'MT'	,	'MLT')	;
INSERT INTO Countries VALUES (	137	,	'Marshall Islands'	,	'MH'	,	'MHL')	;
INSERT INTO Countries VALUES (	138	,	'Martinique'	,	'MQ'	,	'MTQ')	;
INSERT INTO Countries VALUES (	139	,	'Mauritania'	,	'MR'	,	'MRT')	;
INSERT INTO Countries VALUES (	140	,	'Mauritius'	,	'MU'	,	'MUS')	;
INSERT INTO Countries VALUES (	141	,	'Mayotte'	,	'YT'	,	'MYT')	;
INSERT INTO Countries VALUES (	142	,	'Mexico'	,	'MX'	,	'MEX')	;
INSERT INTO Countries VALUES (	143	,	'Micronesia'	,	'FM'	,	'FSM')	;
INSERT INTO Countries VALUES (	144	,	'Moldava'	,	'MD'	,	'MDA')	;
INSERT INTO Countries VALUES (	145	,	'Monaco'	,	'MC'	,	'MCO')	;
INSERT INTO Countries VALUES (	146	,	'Mongolia'	,	'MN'	,	'MNG')	;
INSERT INTO Countries VALUES (	147	,	'Montenegro'	,	'ME'	,	'MNE')	;
INSERT INTO Countries VALUES (	148	,	'Montserrat'	,	'MS'	,	'MSR')	;
INSERT INTO Countries VALUES (	149	,	'Morocco'	,	'MA'	,	'MAR')	;
INSERT INTO Countries VALUES (	150	,	'Mozambique'	,	'MZ'	,	'MOZ')	;
INSERT INTO Countries VALUES (	151	,	'Myanmar (Burma)'	,	'MM'	,	'MMR')	;
INSERT INTO Countries VALUES (	152	,	'Namibia'	,	'NA'	,	'NAM')	;
INSERT INTO Countries VALUES (	153	,	'Nauru'	,	'NR'	,	'NRU')	;
INSERT INTO Countries VALUES (	154	,	'Nepal'	,	'NP'	,	'NPL')	;
INSERT INTO Countries VALUES (	155	,	'Netherlands'	,	'NL'	,	'NLD')	;
INSERT INTO Countries VALUES (	156	,	'New Caledonia'	,	'NC'	,	'NCL')	;
INSERT INTO Countries VALUES (	157	,	'New Zealand'	,	'NZ'	,	'NZL')	;
INSERT INTO Countries VALUES (	158	,	'Nicaragua'	,	'NI'	,	'NIC')	;
INSERT INTO Countries VALUES (	159	,	'Niger'	,	'NE'	,	'NER')	;
INSERT INTO Countries VALUES (	160	,	'Nigeria'	,	'NG'	,	'NGA')	;
INSERT INTO Countries VALUES (	161	,	'Niue'	,	'NU'	,	'NIU')	;
INSERT INTO Countries VALUES (	162	,	'Norfolk Island'	,	'NF'	,	'NFK')	;
INSERT INTO Countries VALUES (	163	,	'North Korea'	,	'KP'	,	'PRK')	;
INSERT INTO Countries VALUES (	164	,	'Northern Mariana Islands'	,	'MP'	,	'MNP')	;
INSERT INTO Countries VALUES (	165	,	'Norway'	,	'NO'	,	'NOR')	;
INSERT INTO Countries VALUES (	166	,	'Oman'	,	'OM'	,	'OMN')	;
INSERT INTO Countries VALUES (	167	,	'Pakistan'	,	'PK'	,	'PAK')	;
INSERT INTO Countries VALUES (	168	,	'Palau'	,	'PW'	,	'PLW')	;
INSERT INTO Countries VALUES (	169	,	'Palestine'	,	'PS'	,	'PSE')	;
INSERT INTO Countries VALUES (	170	,	'Panama'	,	'PA'	,	'PAN')	;
INSERT INTO Countries VALUES (	171	,	'Papua New Guinea'	,	'PG'	,	'PNG')	;
INSERT INTO Countries VALUES (	172	,	'Paraguay'	,	'PY'	,	'PRY')	;
INSERT INTO Countries VALUES (	173	,	'Peru'	,	'PE'	,	'PER')	;
INSERT INTO Countries VALUES (	174	,	'Phillipines'	,	'PH'	,	'PHL')	;
INSERT INTO Countries VALUES (	175	,	'Pitcairn'	,	'PN'	,	'PCN')	;
INSERT INTO Countries VALUES (	176	,	'Poland'	,	'PL'	,	'POL')	;
INSERT INTO Countries VALUES (	177	,	'Portugal'	,	'PT'	,	'PRT')	;
INSERT INTO Countries VALUES (	178	,	'Puerto Rico'	,	'PR'	,	'PRI')	;
INSERT INTO Countries VALUES (	179	,	'Qatar'	,	'QA'	,	'QAT')	;
INSERT INTO Countries VALUES (	180	,	'Reunion'	,	'RE'	,	'REU')	;
INSERT INTO Countries VALUES (	181	,	'Romania'	,	'RO'	,	'ROU')	;
INSERT INTO Countries VALUES (	182	,	'Russia'	,	'RU'	,	'RUS')	;
INSERT INTO Countries VALUES (	183	,	'Rwanda'	,	'RW'	,	'RWA')	;
INSERT INTO Countries VALUES (	184	,	'Saint Barthelemy'	,	'BL'	,	'BLM')	;
INSERT INTO Countries VALUES (	185	,	'Saint Helena'	,	'SH'	,	'SHN')	;
INSERT INTO Countries VALUES (	186	,	'Saint Kitts and Nevis'	,	'KN'	,	'KNA')	;
INSERT INTO Countries VALUES (	187	,	'Saint Lucia'	,	'LC'	,	'LCA')	;
INSERT INTO Countries VALUES (	188	,	'Saint Martin'	,	'MF'	,	'MAF')	;
INSERT INTO Countries VALUES (	189	,	'Saint Pierre and Miquelon'	,	'PM'	,	'SPM')	;
INSERT INTO Countries VALUES (	190	,	'Saint Vincent and the Grenadines'	,	'VC'	,	'VCT')	;
INSERT INTO Countries VALUES (	191	,	'Samoa'	,	'WS'	,	'WSM')	;
INSERT INTO Countries VALUES (	192	,	'San Marino'	,	'SM'	,	'SMR')	;
INSERT INTO Countries VALUES (	193	,	'Sao Tome and Principe'	,	'ST'	,	'STP')	;
INSERT INTO Countries VALUES (	194	,	'Saudi Arabia'	,	'SA'	,	'SAU')	;
INSERT INTO Countries VALUES (	195	,	'Senegal'	,	'SN'	,	'SEN')	;
INSERT INTO Countries VALUES (	196	,	'Serbia'	,	'RS'	,	'SRB')	;
INSERT INTO Countries VALUES (	197	,	'Seychelles'	,	'SC'	,	'SYC')	;
INSERT INTO Countries VALUES (	198	,	'Sierra Leone'	,	'SL'	,	'SLE')	;
INSERT INTO Countries VALUES (	199	,	'Singapore'	,	'SG'	,	'SGP')	;
INSERT INTO Countries VALUES (	200	,	'Sint Maarten'	,	'SX'	,	'SXM')	;
INSERT INTO Countries VALUES (	201	,	'Slovakia'	,	'SK'	,	'SVK')	;
INSERT INTO Countries VALUES (	202	,	'Slovenia'	,	'SI'	,	'SVN')	;
INSERT INTO Countries VALUES (	203	,	'Solomon Islands'	,	'SB'	,	'SLB')	;
INSERT INTO Countries VALUES (	204	,	'Somalia'	,	'SO'	,	'SOM')	;
INSERT INTO Countries VALUES (	205	,	'South Africa'	,	'ZA'	,	'ZAF')	;
INSERT INTO Countries VALUES (	206	,	'South Georgia and the South Sandwich Islands'	,	'GS'	,	'SGS')	;
INSERT INTO Countries VALUES (	207	,	'South Korea'	,	'KR'	,	'KOR')	;
INSERT INTO Countries VALUES (	208	,	'South Sudan'	,	'SS'	,	'SSD')	;
INSERT INTO Countries VALUES (	209	,	'Spain'	,	'ES'	,	'ESP')	;
INSERT INTO Countries VALUES (	210	,	'Sri Lanka'	,	'LK'	,	'LKA')	;
INSERT INTO Countries VALUES (	211	,	'Sudan'	,	'SD'	,	'SDN')	;
INSERT INTO Countries VALUES (	212	,	'Suriname'	,	'SR'	,	'SUR')	;
INSERT INTO Countries VALUES (	213	,	'Svalbard and Jan Mayen'	,	'SJ'	,	'SJM')	;
INSERT INTO Countries VALUES (	214	,	'Swaziland'	,	'SZ'	,	'SWZ')	;
INSERT INTO Countries VALUES (	215	,	'Sweden'	,	'SE'	,	'SWE')	;
INSERT INTO Countries VALUES (	216	,	'Switzerland'	,	'CH'	,	'CHE')	;
INSERT INTO Countries VALUES (	217	,	'Syria'	,	'SY'	,	'SYR')	;
INSERT INTO Countries VALUES (	218	,	'Taiwan'	,	'TW'	,	'TWN')	;
INSERT INTO Countries VALUES (	219	,	'Tajikistan'	,	'TJ'	,	'TJK')	;
INSERT INTO Countries VALUES (	220	,	'Tanzania'	,	'TZ'	,	'TZA')	;
INSERT INTO Countries VALUES (	221	,	'Thailand'	,	'TH'	,	'THA')	;
INSERT INTO Countries VALUES (	222	,	'Timor-Leste (East Timor)'	,	'TL'	,	'TLS')	;
INSERT INTO Countries VALUES (	223	,	'Togo'	,	'TG'	,	'TGO')	;
INSERT INTO Countries VALUES (	224	,	'Tokelau'	,	'TK'	,	'TKL')	;
INSERT INTO Countries VALUES (	225	,	'Tonga'	,	'TO'	,	'TON')	;
INSERT INTO Countries VALUES (	226	,	'Trinidad and Tobago'	,	'TT'	,	'TTO')	;
INSERT INTO Countries VALUES (	227	,	'Tunisia'	,	'TN'	,	'TUN')	;
INSERT INTO Countries VALUES (	228	,	'Turkey'	,	'TR'	,	'TUR')	;
INSERT INTO Countries VALUES (	229	,	'Turkmenistan'	,	'TM'	,	'TKM')	;
INSERT INTO Countries VALUES (	230	,	'Turks and Caicos Islands'	,	'TC'	,	'TCA')	;
INSERT INTO Countries VALUES (	231	,	'Tuvalu'	,	'TV'	,	'TUV')	;
INSERT INTO Countries VALUES (	232	,	'Uganda'	,	'UG'	,	'UGA')	;
INSERT INTO Countries VALUES (	233	,	'Ukraine'	,	'UA'	,	'UKR')	;
INSERT INTO Countries VALUES (	234	,	'United Arab Emirates'	,	'AE'	,	'ARE')	;
INSERT INTO Countries VALUES (	235	,	'United Kingdom'	,	'GB'	,	'GBR')	;
INSERT INTO Countries VALUES (	236	,	'United States'	,	'US'	,	'USA')	;
INSERT INTO Countries VALUES (	237	,	'United States Minor Outlying Islands'	,	'UM'	,	'UMI')	;
INSERT INTO Countries VALUES (	238	,	'Uruguay'	,	'UY'	,	'URY')	;
INSERT INTO Countries VALUES (	239	,	'Uzbekistan'	,	'UZ'	,	'UZB')	;
INSERT INTO Countries VALUES (	240	,	'Vanuatu'	,	'VU'	,	'VUT')	;
INSERT INTO Countries VALUES (	241	,	'Vatican City'	,	'VA'	,	'VAT')	;
INSERT INTO Countries VALUES (	242	,	'Venezuela'	,	'VE'	,	'VEN')	;
INSERT INTO Countries VALUES (	243	,	'Vietnam'	,	'VN'	,	'VNM')	;
INSERT INTO Countries VALUES (	244	,	'Virgin Islands (British)'	,	'VG'	,	'VGB')	;
INSERT INTO Countries VALUES (	245	,	'Virgin Islands (US)'	,	'VI'	,	'VIR')	;
INSERT INTO Countries VALUES (	246	,	'Wallis and Futuna'	,	'WF'	,	'WLF')	;
INSERT INTO Countries VALUES (	247	,	'Western Sahara'	,	'EH'	,	'ESH')	;
INSERT INTO Countries VALUES (	248	,	'Yemen'	,	'YE'	,	'YEM')	;
INSERT INTO Countries VALUES (	249	,	'Zambia'	,	'ZM'	,	'ZMB')	;
INSERT INTO Countries VALUES (	250	,	'Zimbabwe'	,	'ZW'	,	'ZWE')	;
